swagger: "2.0"
info:
  title: sample API
  description: sampleAPI
  version: ""
host: localhost:8000
basePath: /
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - sample
      summary: login sample
      operationId: sample#login
      produces:
      - application/xml
      parameters:
      - name: request_tmp
        in: query
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SampleLoginResponseBody'
      schemes:
      - http
definitions:
  SampleLoginResponseBody:
    title: SampleLoginResponseBody
    type: object
    properties:
      XMLName:
        type: string
        example: Sunt repellat ad saepe minima tempora.
      result_tmp1:
        type: object
        properties:
          result_tmp2:
            type: integer
            example: 3973751882237769319
            format: int64
        example:
          result_tmp2: 6097561127924218507
      result_tmp3:
        type: string
        example: "1987-11-20T13:45:34Z"
        format: date-time
    example:
      XMLName: Quia ipsa dolor hic et asperiores a.
      result_tmp1:
        result_tmp2: 3016041011090759835
      result_tmp3: "2012-03-30T11:04:48Z"
