swagger: "2.0"
info:
  title: sample API
  description: sampleAPI
  version: ""
host: localhost:8000
basePath: /
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - sample
      summary: login sample
      operationId: sample#login
      produces:
      - application/xml
      parameters:
      - name: request_tmp
        in: query
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SampleLoginResponseBody'
      schemes:
      - http
definitions:
  SampleLoginResponseBody:
    title: SampleLoginResponseBody
    type: object
    properties:
      XMLName:
        type: string
        example: Molestiae soluta rem dignissimos.
      result_tmp1:
        type: object
        properties:
          result_tmp2:
            type: integer
            example: 2279190139376579880
            format: int64
        example:
          result_tmp2: 5055606733223162898
      result_tmp3:
        type: integer
        example: 2986734667709101715
        format: int64
    example:
      XMLName: Cumque ipsam vel dolor omnis dignissimos.
      result_tmp1:
        result_tmp2: 3188429226741909665
      result_tmp3: 8735278349679104463
